name: resizesmp
version: '0.0.17-DESTRUCTIVE'
main: me.cooperzilla.resizesmp.ResizeSMP
api-version: '1.20'
commands:
  debug:
    description: debug
    usage: /debug <big/small> | /debug give <revive/size> <optional amount>
    permission: resizesmp.debug
  revive:
    description: debug
    usage: /revive <name>
    permission: resizesmp.revive
  withdraw:
    description: debug
    usage: /withdraw <optional amount>
    permission: resizesmp.withdraw
permissions:
  resizesmp.revive:
    default: true
  resizesmp.withdraw:
    default: true
