name: Build Gradle project
on:
  push:
    branches:
      - master
jobs:
  build-gradle-project:
    name: build plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run compile java
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ResizeSMP
          path: /build/libs/*.jar