name: build pack
on:
  push:
    branches:
      - resource-pack
jobs:
  packsquash:
    name: build pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'pack'
      - name: Upload optimized pack
        uses: actions/upload-artifact@v4
        with:
          compression: 0
          name: pack
          path: /tmp/pack.zip